default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  collation: ja_JP.UTF-8
  template: template0
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: ohnuki_rejob_develop

test:
  <<: *default
  database: ohnuki_rejob_test